server:
  port: 8091
  servlet:
    context-path: /paycenter


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment_center?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
      host: localhost
      password: 123321
      port: 6379
#      namespace: pay-core
#      db: 7

#     expiration-time: 14400
  cloud:
    consul:
        enabled: false

octo:
  host: 127.0.0.1:8000
  key: 01dd2c7e0ed346248fd7f05e4d6d3503
  secret: c99c5291ceb94476a1654cc7da05c343
  base64Secret: Yzk5YzUyOTFjZWI5NDQ3NmExNjU0Y2M3ZGEwNWMzNDM=
  url:
    acm:
      createAccount: /pay-acm/acm/account/per/createAccount
      queryByComUserId: /pay-acm/acm/account/queryByComUserId
      queryCreateByComUserId: /pay-acm/acm/search/queryRegisterPerBalanceByComUserId
      freezeBalance: /pay-acm/acm/core/freezeBalance
      unfrozenBalance: /pay-acm/acm/core/defreezeBalance
      keepAccounts: /pay-acm/acm/core/keepAccount
      queryPayDetail: /pay-acm/acm/search/queryPayDetail
      queryFrozenDetail: /pay-acm/acm/search/queryFrozenDetail
      queryComUserIdByPhoneNumb: /pay-acm/acm/search/queryComUserIdByPhoneNumber
    jiesuan-web:
      queryChannleAccountIdByMerId: /jiesuan-web-dev/api/accountIdByMerId

ons:
  ProducerId: PID_FLOW_TO_PC_TEST
  ConsumerId: CID_FLOW_TO_PC_TEST
  AccessKey: Zyciwrh1k2MKMZqn
  SecretKey: rloLHGvAGTeEphhXflR5tLKFXo3aaN
  Topic: FLOW_TO_PC_TEST