spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
    deserialization:
      fail-on-unknown-properties: false
  aop:
    auto: true
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  application:
    name: pay-core-api
logging:
  config: classpath:log4j2.yml
mybatis:
  mapperLocations: classpath:mybatis/*.xml
  typeAliasesPackage: com.xudq.api.po

